services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME}
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  django:
    build: .
    container_name: django_backend
    command: ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn comments_project.wsgi --bind 0.0.0.0:8000"]
    volumes:
      - .:/app
      - static_data:/app/comments_project/static
      - media_data:/app/comments_project/media
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.local
    container_name: web_nginx
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/static
      - media_data:/media
    depends_on:
      - django
    networks:
      - backend

volumes:
  postgres_data:
  static_data:
  media_data:

networks:
  backend:
    driver: bridge
